### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by NegativeIQ** [Open-GTO/FCNPC#11]
```
=========================== FCNPC Exception Handler ============================
Address: 0x702FD679

Registers:
EAX: 0x0000FFFF - EBX: 0x00000003 - ECX: 0x0071DAE8 - EDX: 0x0012FA00
ESI: 0x00000000 - EDI: 0x2ace848 - EBP: 0x0012F9A0 - ESP: 0x0012F9A0

Stack:
0x0: 0x0012F9B4 - 0x4: 0x702F7404 - 0x8: 0x0000FFFF - 0xC: 0x02ACE848 - 0x10: 0x00000001 - 0x14: 0x00000036
0x18: 0x0046C2E4 - 0x1C: 0x01449458 - 0x20: 0x0012FA00

Information:
  System: Windows
  SA-MP: 0.3.7 R2-1
  FCNPC: 1.0.2

Functions:
  FUNC_CPlayerPool__DeletePlayer: 0x466570
  FUNC_CPlayer__Kill: 0x484620
  FUNC_CPlayer__EnterVehicle: 0x484c70
  FUNC_CPlayer__ExitVehicle: 0x484f50
  FUNC_CPlayer__SpawnForWorld: 0x486d30
  FUNC_GetVehicleModelInfo: 0x488240
  FUNC_CConsole__GetIntVariable: 0x48b5b0
  FUNC_ClientJoin_RPC: 0x4918f0

Pointers:
  VAR_ServerAuthentication: 0x4f5fe8
  VAR_NetVersion: 0xfd9

Offsets:
  OFFSET_RemoteSystemManager: 0x33c
  OFFSET_RemoteSystemSize: 0xcb8
  OFFSET_RemoteSystem__ConnectMode: 0xcb0
  OFFSET_RemoteSystem__Unknown: 0xcb5
=========================== FCNPC Exception Handler ============================
```

Just created simple loader for NPC's and wanted to see if its gonna work as i expected.
Server crashed only after a minute or two without any reason.
Only three functions are used inside filterscript init (no FCNPC publics at all).
FCNPC_Create
FCNPC_Spawn
FCNPC_SetAngle

Plugins list: crashdetect mysql sscanf streamer MapAndreas PathFinder FCNPC
Pretty sure other plugins doesnt have anything to do with it. Also i didnt load height map or init MapAndreas in FCNPC (like i said only 3 functions above are used from FCNPC) .

After that i started server again, tested for like 5 minutes, shooting and killing NPC's, driving over them, not a single problem...

EDIT: Okey...maybe im insane but i just recreated crash, twice... When you drive a bike, and you fell from it (hit something and fly over), server crashes...Insane right? Can someone could confirm these?

EDIT2: Tested everything a little bit more and i concluded that crashes are happening due to player taking damage. (If you bow up yourself with rocked once, server crashes, even if you dont die). I tried to add FCNPC_OnTakeDamage callback and return both 1 or 0, it still crashes. But im now 100% sure its the damage system that makes problems.
